### ISSUE TITLE
disable realtime debugger issue

### ISSUE THREAD

**Issue by AnthonyGillan** [magneto538/Koala#7]
After following the instructions on the Wiki and installing Koala for the first time, when the line `SET_CONDITION(ENABLE_DEBUG)` is removed the compiler throws error:

`CTRL_TOUCHED has not been declared!
(line 2076)
CTRL_TOUCHED := get_ui_id(name)

Koala/debug/debug_user_f.ksp:43`

**Comment by magneto538** [comment]
The fix to this has just been pushed. Please pull the latest version again from GitHub.
Closed.

**Comment by AnthonyGillan** [comment]
Brilliant, thank you for the super quick response!
